# Generated by Django 3.1.5 on 2021-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedwebsites',
            name='datestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
